# A BNF Grammar for BNF Compiler Specifications.
# Version 0.0.8

begin BNF_Grammar

<grammar>      = <blank>? <begin> <statement>+ <end>

<begin>        = "begin" <class_name> <action>? <separator>

<class_name>   = /\A[A-Z][A-Za-z0-9_]*/

<end>          = "end" <action>?

<statement>    = (<rule>) <separator>

<rule>         = <rule_name> "=" <expression>

<rule_name>    = /\A\<[a-z][a-z0-9_]*\>/

<expression>   = <term> ("|" term)*

<term>         = <factor>+

<factor>       = <value> ("?"|"*"|"+")? <action>?

<value>        = (<string> | <regex> | <rule_name> | "(" <expression> ")")

<separator>    = ";" | <blank>

<blank>        = /\A\s*$(^\s*$)+/

<action>       = /\A{{.*}}/m


<spaces>       = /\A\s+/  {{ false }}

<comments>     = /\A#.*$/ {{ false }}

end
